import{a as v,S as E,i as s}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const c of i.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(t){if(t.ep)return;t.ep=!0;const i=e(t);fetch(t.href,i)}})();const B="52944320-b7e1ddf3616ae70650c2bd4af",P="https://pixabay.com/api/",R=15;async function h(o,r=1){const e={key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:R};try{return(await v.get(P,{params:e})).data}catch(n){throw n}}const m=document.getElementById("gallery"),f=document.getElementById("loader"),g=document.getElementById("load-more");let S=new E(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const r=o.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <ul class="info">
        <li><b>Likes</b><div>${e.likes}</div></li>
        <li><b>Views</b><div>${e.views}</div></li>
        <li><b>Comments</b><div>${e.comments}</div></li>
        <li><b>Downloads</b><div>${e.downloads}</div></li>
      </ul>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",r),S.refresh()}function I(){m.innerHTML=""}function p(){f.classList.remove("is-hidden")}function b(){f.classList.add("is-hidden")}function w(){g.classList.remove("is-hidden")}function a(){g.classList.add("is-hidden")}const L=document.getElementById("search-form"),q=L.querySelector('input[name="search-text"]'),$=document.getElementById("load-more");let d="",l=1,u=0;L.addEventListener("submit",async o=>{o.preventDefault();const r=q.value.trim();if(!r){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}d=r,l=1,I(),a(),p();try{const e=await h(d,l);if(u=e.totalHits||0,!e.hits||e.hits.length===0){s.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(e.hits),document.querySelectorAll(".gallery .gallery-item").length<u?w():a()}catch(e){console.error(e),s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}});$.addEventListener("click",async()=>{l+=1,p(),a();try{const o=await h(d,l);if(!o.hits||o.hits.length===0){s.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),a();return}y(o.hits);const r=document.querySelector(".gallery .gallery-item");if(r){const{height:n}=r.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}document.querySelectorAll(".gallery .gallery-item").length>=o.totalHits?(a(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch(o){console.error(o),s.error({title:"Error",message:"Could not load more images.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
